### ISSUE TITLE
Remove useless code climate message

### ISSUE THREAD

**Issue by gearnode** [jobteaser/job_tomate#47]
When i create a pull request, i receive "Code Climate is analyzing this code." message from tomato.

I think this message is useless, it's possible to remove it ?

**Comment by rchampourlier** [comment]
Ok, let's do this 😄 

### What does trigger this Slack notification?

How can we know? JobTomate workflows are built over events. That means that this notification is probably started by an event. Since the event is related to Github, let's have a look into [lib/job_tomate/events/github](https://github.com/jobteaser/job_tomate/tree/master/lib/job_tomate/events/github).

What do we find? 3 events:

- pull request opened
- pull request closed
- status updated

While the event appears to be triggered by opening a pull request, in fact, it's the status updated event instead. Indeed, plugins hooked into Github's workflow (like Codeclimate and CircleCI) trigger these "status updated" events. So let's have a look into the [status updated event handler](https://github.com/jobteaser/job_tomate/blob/master/lib/job_tomate/events/github/status_updated.rb).

What does it tell us? Well, the `run(status)` action only perform a single thing, so it's quite simple: it performs the `SlackNotifyOnGithubStatusUpdate` action! Seems that this is our culprit! Let's have a look at [this action](https://github.com/jobteaser/job_tomate/blob/master/lib/job_tomate/actions/slack_notify_on_github_status_update.rb).

What does the top comment say?

    # Run on Github status update event to notify the corresponding user
    # (the sender of status' pull request).

Well, I think that's it. Apart from finding the author of the update and its Slack username, the main method (`run`) only sends the Slack message. **We can see that there is no filtering on the messages, so any status update received will trigger the Slack message.**

In regard to your requirement, that's what we need to change!

### Doing the change

JobTomate is fairly tested, so we should be able to do some TDD. Let's try to find the matching test. As explained in the README (or the doc/guidelines document), we chose to only use acceptance tests to test workflows. Only commands are unit tested, so we should find the appropriate test in [spec/acceptance](https://github.com/jobteaser/job_tomate/tree/master/spec/acceptance). The event is associated to Github, so let's look into [Github acceptance tests](https://github.com/jobteaser/job_tomate/tree/master/spec/acceptance/github) first.

Bingo 💯 => [status update spec](https://github.com/jobteaser/job_tomate/blob/master/spec/acceptance/github/status_spec.rb).

Well, from now, you should be able to get it from the pull request 😉 .

**Comment by gearnode** [comment]
@rchampourlier thx !
